Transform: AWS::Serverless-2016-10-31

Parameters:
  Roles:
    Type: CommaDelimitedList
    Default: CognitoSAI-FederatedUserRole-3IHKNHJY8G3F,Admin

Resources:
  GlueDatasetAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-access-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: "arn:aws:s3:::awsglue-datasets/*"
      Roles: !Ref Roles